version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    groups:
      development-dependencies:
        dependency-type: development

  - package-ecosystem: bundler
    directory: /examples/dummy_app
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
